#!/usr/bin/env bash
setup(){
	
	#prepare environment and dependencies
#	./installDocker.bin
#	./cloneGit.bin

	#Add container namespaces to host system
	echo "${NAMESPACE} is the namespace!"
	ip netns add $NAMESPACE
	ip netns list
	#create tor/nginx virtual interfaces & make them talk to containers0 [also created]
	ip link add tor0 type veth peer name containers0
	ip link add nginx0 type veth peer name containers0

	#add tor/nginx to namespace
	ip link set tor0 netns $NAMESPACE
	ip link set nginx0 netns $NAMESPACE

	#set nginx/tor IP within namespace
	ip netns exec $NAMESPACE ifconfig tor0 $TOR_IP up
	ip netns exec $NAMESPACE ifconfig nginx $NGINX_IP up

	#Set loopback addr to be a part of container namespace
	ip link set dev lo0 netns $NAMESPACE
	
	#Spin up Nginx Container
	docker run -du $NGINX -p 8080:80 ${SPLASHSCREEN}| sudo tee -a out.txt
	NGINX_ID = out.txt
	wait ${NGINX_ID}
	sudo rm -r out.txt

	#throw an if loop in here somewhere for process validation when starting containers
	#Spin up Tor container when done
	docker run -du -p 8118:8118 -p 9050:9050 $TOR
	curl --proxy localhost:8118 https://www.duckduckgo.com

}

if setup; then
	echo "********************************************"
	echo "This environment is set up and running okay!"
	echo "********************************************"
else
	echo"*******************************************************************"
	echo"Setup error! Refer to other error messages for troubleshooting help"
	echo"*******************************************************************"
fi
